# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"

  webapp:
    build:
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      - mongo
    ports:
      - "8080:8080"
          
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    depends_on:
      - mongo
    ports:
      - "4000:4000"